import type { CareerProfile } from "../../types";

export const CAREER_PROFILES: CareerProfile[] = [
  {
    id: "product-manager",
    career: "Product Manager",
    description: "connecting customer needs, business outcomes, and product delivery",
    skillSignals: ["Product Strategy", "Market Research", "Data Analysis", "Presentation", "Project Management", "Stakeholder Management", "Roadmapping", "Excel"],
    interestSignals: ["Building products", "Solving business problems", "Working with people", "Research and strategy", "Managing projects"],
    orientations: ["business", "balanced"],
    industries: ["Technology", "Mobility", "Automotive", "Consumer", "Finance", "Healthcare", "E-commerce"],
    goals: ["first_job", "career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional", "returning_to_work"],
    relatedRoles: ["Product Manager", "Product Owner", "Product Planning", "Business Analyst", "Project Manager", "Strategy"],
    skillsToLearn: ["Product discovery", "Roadmapping", "User research", "Stakeholder management", "Product analytics"],
  },
  {
    id: "business-analyst",
    career: "Business Analyst",
    description: "translating business needs and evidence into practical improvements",
    skillSignals: ["Excel", "SQL", "Market Research", "Data Analysis", "Presentation", "Project Management", "Process Mapping", "Requirements Analysis"],
    interestSignals: ["Solving business problems", "Working with data", "Research and strategy", "Working with people"],
    orientations: ["business", "balanced"],
    industries: ["Technology", "Finance", "Consulting", "Healthcare", "E-commerce", "Manufacturing", "Automotive"],
    goals: ["first_job", "career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional", "returning_to_work"],
    relatedRoles: ["Business Analyst", "Consultant", "Operations Analyst", "Process Analyst", "Product Planning"],
    skillsToLearn: ["Requirements analysis", "Process mapping", "SQL", "Business case development", "Stakeholder communication"],
  },
  {
    id: "product-analyst",
    career: "Product Analyst",
    description: "using product and customer data to improve digital experiences",
    skillSignals: ["SQL", "Excel", "Data Analysis", "Power BI", "Python", "Product Strategy", "Market Research", "Statistics"],
    interestSignals: ["Working with data", "Building products", "Solving business problems", "Research and strategy"],
    orientations: ["balanced", "technical"],
    industries: ["Technology", "Consumer", "Finance", "E-commerce", "Mobility", "Healthcare"],
    goals: ["first_job", "career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional"],
    relatedRoles: ["Product Analyst", "Data Analyst", "Business Analyst", "Growth Analyst", "Product Operations"],
    skillsToLearn: ["Product metrics", "Experimentation", "Advanced SQL", "Analytics storytelling", "Event tracking"],
  },
  {
    id: "data-analyst",
    career: "Data Analyst",
    description: "turning raw data into clear insights and better decisions",
    skillSignals: ["SQL", "Excel", "Data Analysis", "Power BI", "Python", "Statistics", "Tableau", "Presentation"],
    interestSignals: ["Working with data", "Solving business problems", "Research and strategy"],
    orientations: ["balanced", "technical"],
    industries: ["Technology", "Finance", "Consumer", "Healthcare", "Consulting", "E-commerce", "Manufacturing", "Automotive"],
    goals: ["first_job", "career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional", "returning_to_work"],
    relatedRoles: ["Data Analyst", "Reporting Analyst", "MIS Analyst", "Business Analyst", "Analytics"],
    skillsToLearn: ["Advanced SQL", "Data visualisation", "Statistics", "Data cleaning", "Analytics storytelling"],
  },
  {
    id: "data-scientist",
    career: "Data Scientist",
    description: "building statistical and machine-learning solutions for complex problems",
    skillSignals: ["Python", "SQL", "Data Analysis", "Statistics", "Machine Learning", "R", "Power BI", "Research"],
    interestSignals: ["Working with data", "Writing code", "Research and strategy", "Solving business problems"],
    orientations: ["technical"],
    industries: ["Technology", "Finance", "Healthcare", "Consumer", "E-commerce", "Mobility", "Automotive"],
    goals: ["upskill", "specific_job", "career_switch", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional"],
    relatedRoles: ["Data Scientist", "Machine Learning Engineer", "Research Analyst", "Data Analyst", "AI Engineer"],
    skillsToLearn: ["Machine learning", "Statistics", "Feature engineering", "Model evaluation", "Python data stack"],
  },
  {
    id: "software-engineer",
    career: "Software Engineer",
    description: "designing and building reliable software products and systems",
    skillSignals: ["Python", "JavaScript", "TypeScript", "Java", "React", "SQL", "Git", "Problem Solving", "Data Structures"],
    interestSignals: ["Writing code", "Building products", "Solving business problems"],
    orientations: ["technical"],
    industries: ["Technology", "Finance", "Consumer", "Healthcare", "E-commerce", "Mobility", "Automotive"],
    goals: ["first_job", "career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional", "returning_to_work"],
    relatedRoles: ["Software Engineer", "Developer", "Programmer", "Frontend Engineer", "Backend Engineer", "Full Stack Engineer"],
    skillsToLearn: ["Data structures", "System design", "Testing", "Git workflows", "Production deployment"],
  },
  {
    id: "project-manager",
    career: "Project Manager",
    description: "coordinating people, scope, risk, and delivery across complex initiatives",
    skillSignals: ["Project Management", "Presentation", "Excel", "Stakeholder Management", "Planning", "Risk Management", "Communication", "Agile"],
    interestSignals: ["Managing projects", "Working with people", "Solving business problems", "Research and strategy"],
    orientations: ["business", "balanced"],
    industries: ["Technology", "Mobility", "Automotive", "Finance", "Healthcare", "Consulting", "Manufacturing"],
    goals: ["career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["working_professional", "returning_to_work", "recent_graduate"],
    relatedRoles: ["Project Manager", "Program Manager", "Project Coordinator", "Scrum Master", "Delivery Manager"],
    skillsToLearn: ["Project planning", "Risk management", "Agile delivery", "Budgeting", "Team leadership"],
  },
  {
    id: "ux-designer",
    career: "UX Designer",
    description: "researching user needs and creating intuitive digital experiences",
    skillSignals: ["User Research", "Figma", "Prototyping", "Presentation", "Market Research", "Design Thinking", "Wireframing"],
    interestSignals: ["Designing experiences", "Working with people", "Building products", "Research and strategy"],
    orientations: ["balanced"],
    industries: ["Technology", "Consumer", "Finance", "Healthcare", "E-commerce", "Mobility"],
    goals: ["first_job", "career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional", "returning_to_work"],
    relatedRoles: ["UX Designer", "UI Designer", "Product Designer", "Interaction Designer", "UX Researcher"],
    skillsToLearn: ["User research", "Interaction design", "Prototyping", "Usability testing", "Design systems"],
  },
  {
    id: "operations-manager",
    career: "Operations Manager",
    description: "improving processes, teams, and systems so organisations run effectively",
    skillSignals: ["Excel", "Project Management", "Data Analysis", "Presentation", "Process Improvement", "Planning", "People Management", "Power BI"],
    interestSignals: ["Solving business problems", "Managing projects", "Working with people", "Working with data"],
    orientations: ["business", "balanced"],
    industries: ["Mobility", "Automotive", "Consumer", "Healthcare", "E-commerce", "Manufacturing", "Consulting"],
    goals: ["career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["working_professional", "returning_to_work", "recent_graduate"],
    relatedRoles: ["Operations Manager", "Operations Analyst", "Supply Chain", "Process Manager", "Business Operations"],
    skillsToLearn: ["Process improvement", "Operations analytics", "Resource planning", "People management", "Quality systems"],
  },
  {
    id: "marketing-manager",
    career: "Marketing Manager",
    description: "combining customer insight, creativity, and commercial strategy to grow a brand",
    skillSignals: ["Market Research", "Presentation", "Data Analysis", "Excel", "Digital Marketing", "Content Strategy", "Campaign Management", "Product Strategy"],
    interestSignals: ["Research and strategy", "Working with people", "Solving business problems", "Designing experiences"],
    orientations: ["business", "balanced"],
    industries: ["Technology", "Consumer", "Finance", "Healthcare", "E-commerce", "Mobility", "Automotive"],
    goals: ["first_job", "career_switch", "upskill", "specific_job", "career_discovery", "practical_skills"],
    statuses: ["student", "recent_graduate", "working_professional", "returning_to_work"],
    relatedRoles: ["Marketing Manager", "Digital Marketing", "Brand Manager", "Growth Marketing", "Content Marketing"],
    skillsToLearn: ["Campaign strategy", "Marketing analytics", "Customer segmentation", "Brand positioning", "Channel planning"],
  },
];
